
services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - JWT_SECRET=secret-key
    volumes:
      - ./backend:/app
      - ./db:/db
    ports:
      - 8000:8000